### ISSUE TITLE
Implement IUserTwoFactorStore<TUser>and IUserClaimStore<TUser>

### ISSUE THREAD

**Issue by JokerstudioDev** [lkubis/AspNetCore.Identity.Cassandra#3]
Please implement IUserTwoFactorStore<TUser>and IUserClaimStore<TUser> for login with google

**Comment by lkubis** [comment]
I'm already working on it.

**Comment by JokerstudioDev** [comment]
Thank you :)

**Comment by lkubis** [comment]
Done. You can expect it in the next release.
