### ISSUE TITLE
minor mistake in project wiki

### ISSUE THREAD

**Issue by JohnnyFun** [lkubis/AspNetCore.Identity.Cassandra#4]
On [this page](https://github.com/lkubis/AspNetCore.Identity.Cassandra/wiki/Initial-Setup):

`services.Configure<CassandraOptions>(Configuration.GetSection("CassandraOptions"));`

should be

`services.Configure<CassandraOptions>(Configuration.GetSection("Cassandra"));`

Was correct in the sample app though! 

Thanks for writing this, btw!

**Comment by lkubis** [comment]
It's already fixed. Thanks for using it!
