### ISSUE TITLE
Error with DB initializer UdtMap method on cassandra not found

### ISSUE THREAD

**Issue by MichaelBaarz** [lkubis/AspNetCore.Identity.Cassandra#5]
I try to use the project. When I use the DB initializer as described in the documentation, I got the following error:

> Unhandled exception. System.MissingMethodException: Method not found: 'Cassandra.UdtMap`1<System.__Canon> Cassandra.UdtMap.For(System.String)'.
>    at AspNetCore.Identity.Cassandra.DbInitializer.Initialize[TUser,TRole](CassandraOptions options)
>    at AspNetCore.Identity.Cassandra.Extensions.IWebHostExtensions.InitializeIdentityDb[TUser,TRole](IWebHost host)

Im using version 2.2.0 of the driver in a .NET Core 3.0 application. 

In addition, I wanted to create in the meanwhile the db structure by myself with the provided documentation where you draw the created objects. But the types which are used are left in your documentation (e.g. logininfo).

**Comment by lkubis** [comment]
The library is tested on .NET Core 2.2, not 3.0, so I have to create some showcase to simulate this issue, or could you provide me a link to a repo, where can I simulate it?

Regarding the Data Types, take a look to [**DbInitializer**](https://github.com/lkubis/AspNetCore.Identity.Cassandra/blob/c9b92252ef8f0dbbbabd0a9e2629a7dbf7bfd50d/src/AspNetCore.Identity.Cassandra/DbInitializer.cs#L42)

**Comment by MichaelBaarz** [comment]
Sorry I can’t provide a repo. I played around with it, by using the source code directly and simply switch the .NET version in the csproj file all works well.

/Michael
________________________________
Von: lkubis <notifications@github.com>
Gesendet: Thursday, December 12, 2019 12:33:52 PM
An: lkubis/AspNetCore.Identity.Cassandra <AspNetCore.Identity.Cassandra@noreply.github.com>
Cc: Michael Baarz (External - Capgemini Sverige AB) <michael.baarz@ikea.com>; Author <author@noreply.github.com>
Betreff: Re: [lkubis/AspNetCore.Identity.Cassandra] Error with DB initializer UdtMap method on cassandra not found (#5)


The library is tested on .NET Core 2.2, not 3.0, so I have to create some showcase to simulate this issue, or could you provide me a link to a repo, where can I simulate it?

Regarding the Data Types, take a look to DbInitializer<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flkubis%2FAspNetCore.Identity.Cassandra%2Fblob%2Fc9b92252ef8f0dbbbabd0a9e2629a7dbf7bfd50d%2Fsrc%2FAspNetCore.Identity.Cassandra%2FDbInitializer.cs%23L42&data=02%7C01%7Cmichael.baarz%40ikea.com%7Cec5494e8444646b974e708d77ef72aeb%7C720b637a655a40cf816af22f40755c2c%7C0%7C0%7C637117472348711431&sdata=UXCUn%2Bf8cSs1ZCKFJdXZm37a03e%2BY%2BhK63Nx70oFlcI%3D&reserved=0>
