### ISSUE TITLE
Update to dotnet core 3.1

### ISSUE THREAD

**Issue by Fizzixnerd** [lkubis/AspNetCore.Identity.Cassandra#6]
**ENHANCEMENT REQUEST**

dotnet core 2.2 is now end of life.  Is there any chance this will be able to be moved to the current lts, which is dotnet core 3.1?

**Comment by lkubis** [comment]
I hope that I'll find some time to upgrade it soon :)

**Comment by lkubis** [comment]
@Fizzixnerd btw. this library uses .NET Standard 2.0 that means, you can use .NET Core 2.1 ([LTS](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)) for building your applications. 

~~To allow usage in .NET Core 3.0+ I have to wait until Datastax upgrades its **csharp-driver** to .NET Standard 2.1.~~

**Comment by lkubis** [comment]
Migrated
